micronaut:
  application:
    name: neurobajapi
  router:
    static-resources:
      default:
        paths:
          - classpath:static
        mapping: /static/**/*
        enabled: true

netty:
  default:
    allocator:
      max-order: 3